### ISSUE TITLE
login/register not found on 'Register' link

### ISSUE THREAD

**Issue by tonythomas01** [csett86/gerrit-openshift-quickstart#3]
I just installed the openshift catridge as per https://github.com/csett86/gerrit-openshift-quickstart/blob/master/README.md and gerrit-thinkfoss.rhcloud.com shows the welcome page alright - but when I click on Register or Sign in - I get a 404

**Comment by csett86** [comment]
Good news is: There is a workaround for that: Just enter the login or register URL without any additional parameters: For your app that would be Register at: https://gerrit-thinkfoss.rhcloud.com/register and Login at https://gerrit-thinkfoss.rhcloud.com/login

The reason behind that must be the config of the main reverse proxy on the openshift host machines.

I need to document that known issue, so thanks for reporting it!

**Comment by csett86** [comment]
Got the Register URL wrong: Its https://gerrit-thinkfoss.rhcloud.com/login/register/

**Comment by fbriand** [comment]
Same problem here. And when I go to the right page and try to enter a gmail account, I get the error "Provider is not supported, or was incorrectly entered"

**Comment by csett86** [comment]
Google disabled its OpenID login (https://developers.google.com/identity/protocols/OpenID2Migration), so you need to use a different OpenID provider like Yahoo or Launchpad.

**Comment by csett86** [comment]
Unfortunately you are right. Gerrit does not work with this uneditable reverse proxy setting of open shift.  This wont get fixed for Openshift 2. Maybe it'll work with Openshift 3.
