### ISSUE TITLE
how do you handle the git clone with ssh

### ISSUE THREAD

**Issue by thincal** [csett86/gerrit-openshift-quickstart#4]
if using the ssh to clone the project like this:
```
git clone ssh://admin@gerrit.example.com:29418/hello-gerrit
```
how to configure the route ? how to let it work ? I don't have any idea now, thanks.

**Comment by csett86** [comment]
SSH clone is not supported on openshift, because it requires an additional open port. Clone via https instead.

**Comment by thincal** [comment]
Thanks for your info.
